### PR TITLE
Allow serving local static files from catnip server itself using /files virtual directory.

### PR DESCRIPTION
**Pull request by Dimagog**
This is useful when working on a pure ClojureScript project.
Assuming there is default.htm file in project root dir, simply enter:
http://localhost:12345/files/default.htm in Catnip's browser frame.
Every time you recompile (save) a .cljs file the frame will refresh to reflect the results.
And no additional/standalone http server is necessary.

### CODE REVIEW

**Comment by bodil** [comment]
Making the whole project directory available over HTTP smells a bit like a security issue to me. I'd prefer if this served a configurable subdirectory from a configurable mount point (so it's off by default, as well). The project.clj file would be a good place for that configuration.

**Comment by Dimagog** [comment]
Not sure what changes here with my addition.
If you already have access to http:/localhost:1234 then you can simply press Ctrl-F and open/access all files there anyway. In other words instead of http://localhost:1234/files/a.clj you can use http://localhost:1234/buffers/a.clj.

My understanding here is that security model is based on the fact that we listen on localhost (not 0.0.0.0), so none of this is externally-visible anyway.

**Comment by bodil** [comment]
Hah, very valid point. However, I'd still like this to be configurable - let me see if I can come up with an implementation.

**Comment by Dimagog** [comment]
Thank you for fixing this.

**Pull request closed without merging**
